apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: book-import
  name: book-import
spec:
  replicas: 3
  selector:
    matchLabels:
      name: book-import
  template:
    metadata:
      labels:
        name: book-import
    spec:
      containers:
      - image: docker.com/klakegg/hugo:0.100.2-busybox
        name: book-import
        ports:
        - containerPort: 8080
          name: http-server
